version: '3.9'

services:
  bg-integration-app:
    build: .
    ports:
      - "8010:8010"
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=src
      - PYTHONUNBUFFERED=1
      - USE_MOCK=TRUE
    depends_on:
      - bg-integration-redis
    command: uvicorn main:app --host 0.0.0.0 --port 8010 --reload

  bg-integration-redis:
    image: "redis:alpine"
    ports:
      - "6380:6379"
