version: '3.9'

services:
    bg-integration-app:
        build: .
        ports:
            - "8010:8010"
        volumes:
            - .:/app
        environment:
            - PYTHONPATH=src
            - PYTHONUNBUFFERED=1
        depends_on:
            - bg-integration-redis
        command: uvicorn main:app --host 0.0.0.0 --port 8010 --reload
        networks:
            - bg-integration-network

    bg-integration-redis:
        image: "redis:alpine"
        networks:
            - bg-integration-network

networks:
    bg-integration-network:
        driver: bridge